### ISSUE TITLE
Feature request: Write advice in markdown syntax

### ISSUE THREAD

**Issue by stevew00ds** [vmware-tanzu/cloud-suitability-analyzer#50]
Ability to write rule advice in markdown

```
name: Java-Encoding-Utf8
filepatterns:
  - server/start.sh
target: file
type: not_contains
criticality: high
category: runtime
advice: add '-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8' arguments to the java runtime see [https://www.weather.com](starter changelog)
effort: 1
readiness: 0
tags:
  - value: runtime
patterns:
  - value: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
```
