### ISSUE TITLE
Feature request: New rule type 4

### ISSUE THREAD

**Issue by stevew00ds** [vmware-tanzu/cloud-suitability-analyzer#53]
```
name: Atlas-Framework-Upgrade
filepatterns:
  - /build.gradle
type: not_regex
criticality: high
defaultpattern: '%s\s*=\s*"4.3.7-2.3.6"'
category: build
advice: atlas-framework version should be >= 4.3.7-2.3.6
effort: 1
readiness: 0
tags:
  - value: 4.0.0
patterns:
  - value: atlasFrameworkVersion
```
