### ISSUE TITLE
Feature request: New rule type 5

### ISSUE THREAD

**Issue by stevew00ds** [vmware-tanzu/cloud-suitability-analyzer#54]
```
name: Symphony-Ignite-Segmentation
filepatterns:
  - "**/application.yaml"
  - "**/application.yml"
  - "**/application-test.yaml"
  - "**/application-test.yml"
type: not_contains_yaml
criticality: high
yamlpath:
  - symphony.ignite.app-container-name
category: runtime
advice: add symphony.ignite.app-container=<serviceName> to the service application.yaml
effort: 1
readiness: 0
tags:
  - value: 4.0.0
recipes:
  - uri: "https://gitlab.eng.vmware.com/cmbu/cmf-spring-common/blob/master/CHANGELOG.md#breaking-changes-to-symphonyigniteproperties"
```
